### ISSUE TITLE
[DISCORD] : Make the village and market text channels only visible to those with the corresponding villager role.

### ISSUE THREAD

**Issue by Haikuno** [douglasparker/naruto-evolution-community#21]
Title.

**Comment by douglasparker** [comment]
I was discussing with @IllusiveBIair about being able to link your character to your Discord account, and automatically getting the village role according to your in-game character. This in itself should be feasible at some point.

However, I wanted to expand on that by making it possible for in-game village chat to appear on Discord, and village chat in Discord appearing in-game. This may never happen simply because it makes it easier for people to spy on channels while not even logged into the game.

We'll have to consider our options at a later date. I'd personally like to see more Discord integration within the game itself.

**Comment by douglasparker** [comment]
Village and market channels were removed until we can have proper Discord integration.
