### ISSUE TITLE
Make lvling easier/increase stat gains

### ISSUE THREAD

**Issue by GreedCMD** [douglasparker/naruto-evolution-community#49]
**Feature Request:**
I had made a new character to see what the new nerfs too training were like and it's very slow now, new players wont be able to keep up, with the people that abused the increased gains in the first few days and it's made things very unbalanced and un fun for new players. I'd increase the training rate by 50% so new players or people making alts can catch up to the players already maxed out or make chakra infusion give more stats or make it easier to press cause for me it's a bit to fast and I'm sure others could say the same.

**Support this Feature Request:**
Please react to this issue with a 👍🏽 or 👎🏽 to show your support for this feature request.

Please leave a comment 💬 as your feedback is valuable 💎 and will be considered when making development decisions.

**Comment by IllusiveBIair** [comment]
I understand the points here however I'm not going to be making updates to the game's leveling curve based on the cause and effect of past resolved issues. Currently, it's about creating the best balance and leveling curve possible under the assumption that no issues are there to taint it. This is because once everything is fully stable a wipe will be happening where all that corruption will be completely gone. This strategy will only work if we're not distracted by trying to make the best of a bad situation and instead work to create the best possible situation when that wipe occurs. Currently, I understand it's difficult to catch up to the players who had it easy using the training bugs early on but this will be the best way to make sure that no one has an unfair advantage when the playtesting phase is over. However, bearing all that in mind if you still think there are changes that need to be made please do elaborate.
