### ISSUE TITLE
Squad Management

### ISSUE THREAD

**Issue by Noxtyr** [douglasparker/naruto-evolution-community#80]
**Feature Request:**
It would be nice if any Squad member could accept missions independently.
As for balance, the reward would have been divided and small amount of money and exp would have been deducted as a "tax" or "share" to the village.
Perhaps in the future there could be an option to actually use the funds to make custom NPCs like guards, shopkeepers, etc.

**Support this Feature Request:**
Please react to this issue with a 👍🏽 or 👎🏽 to show your support for this feature request.

Please leave a comment 💬 as your feedback is valuable 💎 and will be considered when making development decisions.

**Comment by IllusiveBIair** [comment]
Missions used to be handled independently however it would usually boil down to people doing what was dubbed 'leeching' missions where people go afk and just receive the exp without contributing. It would lead to people gaining less exp because of leechers. With the new way you get much more exp for a single completion but rather than everyone having to keep track of their missions and going their separate ways you can work together to complete the missions and if someone is leeching no one misses out because of it. 

When there are more players online it will be common for people to attack you while you're doing missions as you get exp for assaulting people's missions as well. So generally it will be harder to complete missions solo.

The other issue with it is the idea that you might be trying to do a higher-ranked mission and someone else chooses a lower rank one. It just makes more sense to allow the squad leader to choose the mission in my opinion.

Let me know what you think of those issues and whether or not you have any counterpoints.

**Comment by douglasparker** [comment]
> How about making the highest level online member able to take missions if leader is offline but only as high as their own rank?

Why not just form a new Squad?

**Comment by Noxtyr** [comment]
Say you make a squad with your buddies. Leader goes offline, squad disbands. You form new squad with remaining buddies, maybe invite other guy to join along. Cycle continues. It's just annoying quality of life kind of thing.

**Comment by Noxtyr** [comment]
Fair play.
